### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by KluSim** [luboslenco/add_mesh_LowPolyFactory#1]
Hi! I wanted to try out the addon featured in "8 minutes of Armory", so I clicked the link in the description, pressed "clone or download"-download .zib. Then I went into Blender and tried to install it the usual way, but when trying to tick the checkbox before its name the console gives this error:
`Traceback (most recent call last):
  File "D:\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\lowpolyfactory-master\__init__.py", line 34, in <module>
    from add_mesh_LowPolyFactory import LowPolyFactory
ImportError: No module named 'add_mesh_LowPolyFactory'`
The same happens in armory.

**Comment by luboslenco** [comment]
Hey @Simonrazer, I fixed the module so it should install right away. Does it work now when you re-download as .zip?

**Comment by KluSim** [comment]
No, it wont show up in the addon-list when I selected it and click "Install addon from file"

**Comment by luboslenco** [comment]
Alright, should really work now - download `add_mesh_LowPolyFactory.zip` from https://github.com/luboslenco/add_mesh_LowPolyFactory/releases.

**Comment by KluSim** [comment]
Yes it does!
